### ISSUE TITLE
Paralysis removal.

### ISSUE THREAD

**Issue by peonso** [TwistedScorpio/OTHire#146]
While using instant spell paralysis is removed instantly, while using runes it does not happen though, there is a small delay.

After using _exura_ your next step is at regular speed, the paralysis icon is removed instantly.

While using _ultimate healing rune_ the icon is not removed instantly, and only after it disappears the character comes back to regular speed.

**Comment by peonso** [comment]
This shouldn't exists also:

https://github.com/TwistedScorpio/OTHire/blob/3ff6a46c62486e9f0ae9a6757af3a5b9e83fea85/source/player.cpp#L3876-L3881

**Comment by babymannen** [comment]
So which one is the correct? Should there be a delay or not? I guess not due to the way you are describing it. 

What happens if you add to onCastSpell:

if hasCondition(cid, CONDITION_PARALYZE) then
    doRemoveCondition(cid, CONDITION_PARALYZE)
end

I guess the same, but I have seen people using this method before and I never fully understood why.

**Comment by peonso** [comment]
@babymannen 

I was describing the bug. I couldn't predict any backlash from the commit I made, the behavior with it seems to mimic the one from 7.7 leaked server, runes working as instant spells to remove paralysis.
