### ISSUE TITLE
Field runes remove campfires

### ISSUE THREAD

**Issue by ghost** [TwistedScorpio/OTHire#39]
Field runes, Magic Wall and Wild Growth remove campfire items; `1423, 1424, 1425`.

**Comment by Nottinghster** [comment]
An easy fix ;)

Go to items.xml and found those IDs mentioned by you (1423, 1424, 1425)
Set this attribute to them: <attribute key="type" value="magicfield"/>

Now save your items.xml

Now go to folder Spells and found the file destroy_field_rune.lua, open it

Add this:
local CAMPFIRE = {1423, 1424, 1425}

Now replace that line:
if(field.itemid ~= 0 and (field.itemid < ITEM_SEARINGFIRE_STAGE_FIRST or field.itemid > ITEM_SEARINGFIRE_STAGE_LAST)) then

For that one:
if(field.itemid ~= 0 and (field.itemid < ITEM_SEARINGFIRE_STAGE_FIRST or field.itemid > ITEM_SEARINGFIRE_STAGE_LAST) and (not isInArray(CAMPFIRE, field.itemid))) then

Done, campfires will be not removed if you use destroy field rune on them ;)

**Comment by tarantonio** [comment]
I can't reproduce this bug, my destroy field rune isn't removing campfires. The problem itself it's that when you place a field(energy,fire,...) on campfire(1423,1424,1425) it removes campfire. I don't remember if it's intended or not

**Comment by Emky** [comment]
it's like this for me atm
http://imgur.com/EdsZQe3

**Comment by tarantonio** [comment]
But it's not destroy_field_rune that is causing the problem, it's the fire_field_rune itself that destroys campfires.

**Comment by TwistedScorpio** [comment]
Check if this answer of mine: https://otland.net/threads/7-72-othire-0-0-1b-based-in-otserv-trunk-latest.212153/page-66#post-2337328 seems to solve your problem.

**Comment by Emky** [comment]
**items.xml**
Remove the "field" attribute for the camp fires

**movements/movements.xml**

	<moveevent event="StepIn" itemid="1423" script="campfire.lua" />

	<moveevent event="StepIn" itemid="1424" script="campfire.lua" />

	<moveevent event="StepIn" itemid="1425" script="campfire.lua" />

**movements/scripts/campfire.lua**


	local combat = createCombatObject()
	setCombatParam(combat, COMBAT_PARAM_TYPE, COMBAT_FIREDAMAGE)
	setCombatParam(combat, COMBAT_PARAM_EFFECT, CONST_ME_HITBYFIRE)
	setCombatParam(combat, COMBAT_PARAM_DISTANCEEFFECT, CONST_ANI_FIRE)
	setCombatParam(combat, COMBAT_PARAM_PZBLOCK, 1)

	function onStepIn(cid, item, topos, frompos)
		if isPlayer(cid) then
			doTargetCombatHealth(cid,  COMBAT_FIREDAMAGE, -20, -20, CONST_ME_HITBYFIRE)
			doAddCondition(cid, combat)
		end
		return true
	end

If there is anything i can improve in this script let me know!

**Comment by tarantonio** [comment]
I'll check it later this night

**Comment by tarantonio** [comment]
Working like a charm!

**Comment by peonso** [comment]
Applaying @Emky fix make monsters avoid campfires, even immune ones.

**Comment by peonso** [comment]
The actual bug is field runes removing campfire items. @Emky fix TwistedScorpio/OTHire#39 (comment) actually bug monsters, that will avoid pathing through campfires despite being immune to it. Since removing "block path" flag from campfires make not immune monsters ignore it and be damaged, not a correct behavior.

The way OTHire is coded, you either have campfires as magicfields and they will be replaced by fields/magic wall/wild growth, or you remove it and have monster path fiding behavior bug. Better workaround I could think of would be to make an work arround in https://github.com/TwistedScorpio/OTHire/blob/b78fbbce9e78b1275806cd43005dde568fca4c59/source/combat.cpp#L703 so tiles with campfires 1423, 1424, 1425 are ignored by fields/magic wall/wild growth (what was/is probably default tibia behavior).

@diegorodriguesvieira @babymannen

**Comment by peonso** [comment]
Default tibia behavior is actually having fields being placed above campfires.
